// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import ScrollelementController from "./scrollelement_controller"
application.register("scrollelement", ScrollelementController)


import SimpleformcardsController from "./simpleformcards_controller"
application.register("simpleformcards", SimpleformcardsController)

import VideoController from "./video_controller"
application.register("video", VideoController)
